# Generated by Django 5.2.4 on 2025-09-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expertise',
            field=models.CharField(blank=True, choices=[('W&B', 'Weight & Balance'), ('Route', 'Route'), ('Terrain', 'Terrain'), ('Navigation', 'Navigation'), ('Fuel', 'Fuel')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('worker', 'Worker')], max_length=20, null=True),
        ),
    ]
