# Generated by Django 5.2.5 on 2025-09-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasksubitem',
            unique_together={('task', 'content')},
        ),
    ]
