# Generated by Django 5.2.4 on 2025-09-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_todayreport_delete_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='todayreport',
            name='jira_task_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='todayreport',
            name='progress_made',
            field=models.BooleanField(default=False),
        ),
    ]
