# Generated by Django 5.2.4 on 2025-09-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_todayreport_jira_task_key_todayreport_progress_made'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro')], default='basic', max_length=50),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('worker', 'Worker')], default='worker', max_length=50),
        ),
    ]
